# -*- coding: utf-8 -*-
"""task2_Stock_Portfolio_Tracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YPYJr8JzUneXOo5XkFDeHLdecB_PRTH6
"""

class StockPortfolioTracker:
  def __init__(self):
    self.portfolio = {}
    self.total_portfolio_value = 0.0
    self.instructions()
    print("Welcome to your Stock Portfolio Tracker!")

  def instructions(self):
    print("\n--- Instructions ---")
    print("1. To add a new stock, use the 'add_stock' function.\n   (e.g., tracker.add_stock('AAPL', 10, 150.00))")
    print("2. To get a summary of your portfolio, use the 'summary' function.\n   (e.g., tracker.summary())")
    print("3. To see the details of an individual stock, use 'individual_stock_investment'.\n   (e.g., tracker.individual_stock_investment('AAPL'))")
    print("4. To get your total investment value, use 'total_stock_investment'.\n   (e.g., tracker.total_stock_investment())")
    print("5. To save your portfolio, use 'file_save'.\n   (e.g., tracker.file_save('my_portfolio.txt'))")
    print("--------------------")

  def validate_stock_name(self, stock_name):
    if not isinstance(stock_name, str) or not stock_name.strip():
      print("Error: Stock name must be a non-empty string.")
      return False
    return True

  def validation_quantity_input(self, quantity):
    try:
      quantity = int(quantity)
      if quantity <= 0:
        print("Error: Quantity must be a positive whole number.")
        return False
      return True
    except ValueError:
      print("Error: Quantity must be a whole number.")
      return False

  def validate_price_input(self, price):
    try:
      price = float(price)
      if price <= 0:
        print("Error: Price must be a positive number.")
        return False
      return True
    except ValueError:
      print("Error: Price must be a number.")
      return False

  def add_stock(self, stock_name, quantity, purchase_price):
    if not self.validate_stock_name(stock_name):
      return
    if not self.validation_quantity_input(quantity):
      return
    if not self.validate_price_input(purchase_price):
      return

    stock_name = stock_name.upper() # Standardize stock names
    quantity = int(quantity)
    purchase_price = float(purchase_price)

    if stock_name in self.portfolio:
      # If stock already exists, update quantity and re-calculate average price
      existing_quantity = self.portfolio[stock_name]['quantity']
      existing_total_cost = self.portfolio[stock_name]['quantity'] * self.portfolio[stock_name]['purchase_price']

      new_total_quantity = existing_quantity + quantity
      new_total_cost = existing_total_cost + (quantity * purchase_price)
      new_average_price = new_total_cost / new_total_quantity

      self.portfolio[stock_name]['quantity'] = new_total_quantity
      self.portfolio[stock_name]['purchase_price'] = new_average_price
      print(f"Updated {stock_name}: New quantity {new_total_quantity} at average price ${new_average_price:.2f}")
    else:
      # Add new stock
      self.portfolio[stock_name] = {
          'quantity': quantity,
          'purchase_price': purchase_price
      }
      print(f"Added {quantity} shares of {stock_name} at ${purchase_price:.2f} each.")
    self.update_total_portfolio_value()

  def update_total_portfolio_value(self, current_prices=None):
    """ Updates the total portfolio value.
        If current_prices (dict: {stock_name: current_price}) is provided, uses them.
        Otherwise, uses purchase price as current price for value calculation.
    """
    self.total_portfolio_value = 0.0
    for stock, data in self.portfolio.items():
      if current_prices and stock in current_prices:
        current_price = current_prices[stock]
      else:
        current_price = data['purchase_price'] # Fallback to purchase price if no current price given
      self.total_portfolio_value += data['quantity'] * current_price

  def summary(self):
    print("\n--- Portfolio Summary ---")
    if not self.portfolio:
      print("Your portfolio is currently empty. Add some stocks!")
      return

    for stock, data in self.portfolio.items():
      investment = data['quantity'] * data['purchase_price']
      print(f"Stock: {stock}, Shares: {data['quantity']}, Avg. Price: ${data['purchase_price']:.2f}, Total Investment: ${investment:.2f}")
    self.total_stock_investment()
    print("------------------------")

  def individual_stock_investment(self, stock_name):
    if not self.validate_stock_name(stock_name):
      return
    stock_name = stock_name.upper()
    print(f"\n--- Details for {stock_name} ---")
    if stock_name in self.portfolio:
      data = self.portfolio[stock_name]
      investment = data['quantity'] * data['purchase_price']
      print(f"Shares: {data['quantity']}")
      print(f"Average Purchase Price: ${data['purchase_price']:.2f}")
      print(f"Total Investment in {stock_name}: ${investment:.2f}")
    else:
      print(f"Stock '{stock_name}' not found in your portfolio.")
    print("------------------------")

  def total_stock_investment(self):
    self.update_total_portfolio_value() # Ensure total is updated, using purchase price for simplicity
    print(f"\nTotal Portfolio Value (based on purchase prices): ${self.total_portfolio_value:.2f}")

  def file_save(self, filename='portfolio.txt'):
    try:
      with open(filename, 'w') as f:
        f.write("Stock Portfolio Report\n")
        f.write("--------------------\n")
        if not self.portfolio:
          f.write("Portfolio is empty.\n")
        else:
          for stock, data in self.portfolio.items():
            investment = data['quantity'] * data['purchase_price']
            f.write(f"Stock: {stock}, Shares: {data['quantity']}, Avg. Price: ${data['purchase_price']:.2f}, Total Investment: ${investment:.2f}\n")
          f.write("--------------------\n")
          f.write(f"Total Portfolio Value (based on purchase prices): ${self.total_portfolio_value:.2f}\n")
      print(f"Portfolio successfully saved to {filename}")
    except IOError as e:
      print(f"Error: Could not save portfolio to file '{filename}'. Reason: {e}")




tracker = StockPortfolioTracker()
tracker.add_stock('AAPL', 10, 150.00)
tracker.add_stock('GOOG', 5, 2500.50)
tracker.add_stock('MSFT', 20, 300.25)
tracker.add_stock('AAPL', 5, 155.00) # Adding more AAPL shares

tracker.summary()
tracker.individual_stock_investment('GOOG')
tracker.individual_stock_investment('AMZN') # Stock not in portfolio
tracker.total_stock_investment()
tracker.file_save('my_portfolio_report.txt')

tracker.add_stock('', 10, 100) # Invalid stock name
tracker.add_stock('TSLA', 0, 100) # Invalid quantity
tracker.add_stock('TSLA', 10, -50) # Invalid price
tracker.add_stock('TSLA', 'abc', 100) # Invalid quantity type
tracker.add_stock('TSLA', 10, 'xyz') # Invalid price type