# -*- coding: utf-8 -*-
"""task4_Basic_chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YPYJr8JzUneXOo5XkFDeHLdecB_PRTH6
"""

import random

class ChatBot:
    def __init__(self):
        self.context = {
            "greeted": False,
            "asked_status": False
        }

        self.intents = {
            "greeting": ["hi", "hello", "hey", "hola"],
            "status": ["how are you", "how are you doing", "how's it going"],
            "bye": ["bye", "exit", "quit", "goodbye"],
            "thanks": ["thanks", "thank you"]
        }

        self.responses = {
            "greeting": ["Hi!", "Hello!", "Hey there!"],
            "status": ["I'm doing great 😊", "All good! How about you?", "I'm fine, thanks for asking!"],
            "thanks": ["You're welcome!", "Happy to help 😊"],
            "bye": ["Goodbye! 👋", "See you soon!", "Take care!"],
            "unknown": ["I didn't understand that 🤔", "Can you rephrase?", "I'm not sure about that."]
        }

    # Normalize input
    def clean_input(self, user_input):
        return user_input.lower().strip()

    # Detect intent
    def detect_intent(self, user_input):
        for intent, keywords in self.intents.items():
            for keyword in keywords:
                if keyword in user_input:
                    return intent
        return "unknown"

    # Generate response
    def generate_response(self, intent):
        if intent == "greeting" and self.context["greeted"]:
            return "We already said hello 😊"

        if intent == "greeting":
            self.context["greeted"] = True

        if intent == "status":
            self.context["asked_status"] = True

        return random.choice(self.responses.get(intent, self.responses["unknown"]))

    # Start chatbot
    def start_chat(self):
        print("ChatBot 🤖: Hello! Type 'bye' to exit.\n")

        while True:
            user_input = input("You: ")
            cleaned = self.clean_input(user_input)
            intent = self.detect_intent(cleaned)

            if intent == "bye":
                print("ChatBot 🤖:", random.choice(self.responses["bye"]))
                break

            response = self.generate_response(intent)
            print("ChatBot 🤖:", response)


# Run chatbot
bot = ChatBot()
bot.start_chat()