# -*- coding: utf-8 -*-
"""task1_Hangman_game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YPYJr8JzUneXOo5XkFDeHLdecB_PRTH6
"""

import random

class Hangman:
    def __init__(self, word_list, attempts=6):
        self.word_list = [word.upper() for word in word_list]
        self.attempts = attempts
        self.secret = ''
        self.display_word = []
        self.guessed_letters = set()

    def game_initialization(self) :
        self.secret = random.choice(self.word_list)
        self.display_word = ["_" for _ in self.secret]
        self.guessed_letters = set()
        self.attempts = 6 # Reset attempts for a new game
        print("\n--- Welcome to Hangman! ---")
        print(f"The secret word has {len(self.secret)} letters.")
        print(f"{' '.join(self.display_word)}")

    def current_status(self):
        print(f"\nWord: {' '.join(self.display_word)}")
        print(f"Attempts left: {self.attempts}")
        print(f"Guessed letters: {', '.join(sorted(list(self.guessed_letters)))}")

    def user_guess(self):
        while True:
            guess = input("Guess a letter (or type 'hint' for a clue): ").upper()
            if guess == 'HINT':
                return 'HINT'
            if self.validation(guess):
                return guess

    def validation(self, guess):
        if not guess.isalpha() or len(guess) != 1:
            print("Invalid input. Please enter a single letter.")
            return False
        elif guess in self.guessed_letters:
            print(f"You already guessed '{guess}'. Try again.")
            return False
        return True

    def guess_process(self, guess):
        self.guessed_letters.add(guess)
        if guess in self.secret:
            print(f"Good guess! '{guess}' is in the word.")
            for i, letter in enumerate(self.secret):
                if letter == guess:
                    self.display_word[i] = guess
        else:
            print(f"Sorry, '{guess}' is not in the word.")
            self.attempts -= 1

    def game_loop_status(self):
        return self.attempts > 0 and "_" in self.display_word

    def end_game(self):
        if "_" not in self.display_word:
            print(f"\nCongratulations! You guessed the word: {self.secret}")
            return True
        else:
            print(f"\nGame Over! The secret word was: {self.secret}")
            return False

    def hint(self):
        unguessed_letters = [letter for letter in self.secret if letter not in self.guessed_letters]
        if unguessed_letters:
            hint_letter = random.choice(unguessed_letters)
            print(f"Hint: One of the letters is '{hint_letter}'.")
            self.guess_process(hint_letter) # Automatically add hint to guessed letters
        else:
            print("No more hints available!")

    def replay(self):
        choice = input("Play again? (yes/no): ").lower()
        return choice == 'yes'


word_list = ['python', 'programming', 'developer', 'algorithm', 'computer', 'artificial', 'intelligence']
game = Hangman(word_list)

while True:
    game.game_initialization()
    while game.game_loop_status():
        game.current_status()
        guess = game.user_guess()
        if guess == 'HINT':
            game.hint()
        else:
            game.guess_process(guess)

    # The game has ended (either won or lost)
    game.end_game()
    if not game.replay():
        break

print("Thanks for playing!")